### PR TITLE
initrd/bin/config-gui.sh: Allow configuring automatic boot

### LINKED ISSUE #1441: Add `export CONFIG_AUTO_BOOT_TIMEOUT=5` to all board configs
**Is your feature request related to a problem? Please describe.**
heads doesn't start the boot process without user interaction.

**Describe the solution you'd like**
Add an option like `GRUB_TIMEOUT` to execute the default boot after some time, if that's defined and all verifications succeed.

**Additional context**
I'd also like an option to boot after that timeout even if verification fails as that would help with testing.
~~However imho such an option breaks the heads security model as an attacker could simply enable it and then lure the user into auto-booting.~~
EDIT: After giving it some more thought, I believe that such an option should be possible as an attacker can modify the firmware any way s/he wants anyway, The user will still have to manually check the HOTP/TOTP dongle to make sure that doesn't happen.

### PR DESCRIPTION
**Pull request by JonathonHall-Purism**
Automatic boot can be configured in the configuration GUI.  Options are disable, 1 second, 5 seconds, or 10 seconds.

Users asked me for this :grin: 

Closes #1441 (where @3hhh request for 3s is not in yet, but PR welcome)

### CODE REVIEW

**Comment by tlaurion** [comment]
@JonathonHall-Purism I love this.

Please cherry-pick https://github.com/tlaurion/heads/tree/enable_autoboot_5_seconds_for_hotp_boards 's https://github.com/tlaurion/heads/commit/f189363c44ec667f4280e79888d980c0ad58e847

**Review by tlaurion — CHANGES_REQUESTED** [review]
LGTM with https://github.com/tlaurion/heads/commit/f189363c44ec667f4280e79888d980c0ad58e847 added in (tested under qemu-coreboot-whiptail-tpm2-hotp)

**Comment by JonathonHall-Purism** [comment]
Thanks, picked that commit @tlaurion .

**Review by tlaurion — APPROVED** [review]

**Comment by tlaurion** [comment]
Edited OP to state this closes  #1441 upon merge.

**Pull request merged**
