### PR TITLE
Alexgithublab: change time (superseeds #1730)

### PR DESCRIPTION
**Pull request by tlaurion**
This is PR superseding #1730 

This add helper to change system time clock engaging user into coonsulting external source of time in UTC and setting system time accordingly quite easily, thanks to @alex-nitrokey contribution under #1730.
Screenshots of changed UX at https://github.com/linuxboot/heads/pull/1737#issuecomment-2256118049

---

@alex-nitrokey please comment and approve PR. 
@JonathonHall-Purism please acknowledge/suggest changes so that you are ok with wording prior of merge.

### CODE REVIEW

**Comment by tlaurion** [comment]
@JonathonHall-Purism please review

**Comment by tlaurion** [comment]
@alexgithublab your commits were not signed, force pushing.

**Comment by tlaurion** [comment]
@alexgithublab your commits were not signed (DCO failing on github action see your ofirinal PR), force pushing to limit maintainership time and back and forths, please review https://github.com/linuxboot/heads/blob/master/CONTRIBUTING.md and the changes in this PR.

**Comment by tlaurion** [comment]
So the new UX following this PR looks like.

A gentle reminder that you can do those tests and generate the same screenshots i'm doing here by iteratively testing UX changes and see if they fit smaller screens and all by simply doing (with qemu variants of your choice)

```
docker run -e DISPLAY=$DISPLAY --network host --rm -ti -v $(pwd):$(pwd) -w $(pwd) tlaurion/heads-dev-env:latest -- make BOARD=qemu-coreboot-whiptail-tpm1
docker run -e DISPLAY=$DISPLAY --network host --rm -ti -v $(pwd):$(pwd) -w $(pwd) tlaurion/heads-dev-env:latest -- make BOARD=qemu-coreboot-whiptail-tpm1 run
```

New option under Options menu:

**Comment by alexgithublab** [comment]
@tlaurion 

Sorry for the DCO.. It's weird bc I see my commits signed, I don't know what I'm missing here.

Thanks for the reminder.

>  this affects older hardware more than newer ones

Not necessary for example on new ones Ethernet cable is not working within Heads, now we have USB tethering but this not very convenient to set and also you need to have a compatible phone.

**Comment by tlaurion** [comment]
> @tlaurion
> 
> Sorry for the DCO.. It's weird bc I see my commits signed, I don't know what I'm missing here.
> 
> Thanks for the reminder.

DCO error goes in details on why its missing. This is git `commit --signoff -m`, but please read https://github.com/linuxboot/heads/runs/27905997389 which was given on your oiginal PR.


> 
> > this affects older hardware more than newer ones
> 
> Not necessary for example on new ones Ethernet cable is not working within Heads, now we have USB tethering but this not very convenient to set and also you need to have a compatible phone.

Sorry, I meant clock drifting is more related to older hardware, at least form my experience going over and over explaining this, both because drifting seems to go faster on old platforms and also that older platforms seem to have a tendency to be less often connected to network and as a result less NTP time corrected through wifi.

Yes, Ethernet is fading out, as for Tethering, please open issues to facilitate its usage or comment existing issue to improve its documentation at https://github.com/linuxboot/heads-wiki/issues/149 or open a code/pr to improve UX directly in code.


@alexgithublab are you ok with the changes in this PR against your original code?
- TOTP mismatch placing of change-time call and changes of UX there (considering TOTP mismatch should be entry for changing system time: agree/disagree?
- Removal of duplicate menu entry to change system time
- changes in wording/syntax

Is short, is this ready to be reviewed by other stakeholders to your eyes because Heads master shared between many OEM now, so this needs to be ok between us and reviewed with other suggestions taken so that UX is simplified, not complexified more and none of us are still UX experts. Would be nice if one was appointed to help us improve things in this area, I know none.

**Comment by tlaurion** [comment]
@alexgithublab if you're ok with my changes, please approve this PR to that other stakeholders can approve. Also please test this into qemu so that you can aksowledge what is expected by contributors for testing their changes themselves for future PR from your side and reduce my involvement into finding chmod +x issues, then functional testing, then exposing UX changes then doing code review etc.

**Comment by tlaurion** [comment]
@alexgithublab maybe change-time should remind actual system clock prior of change?

**Review by alexgithublab — APPROVED** [review]

**Review by alexgithublab — APPROVED** [review]

**Comment by tlaurion** [comment]
> @JonathonHall-Purism please review

@JonathonHall-Purism ping

**Comment by JonathonHall-Purism** [comment]
> @JonathonHall-Purism ping

Sorry for the delay here but I'm taking a look, nice work all.  I would like to propose some wording improvements, will test and provide a commit, should be ready tomorrow.

**Comment by JonathonHall-Purism** [comment]
@tlaurion @alexgithublab I made some improvements and proposed them in #1748.  Thanks for all the work on this!

If you'd rather pull changes over to this PR though (and/or discuss of course), that's fine too.

**Pull request merged**
