### PR TITLE
Port heads to system76 galago pro 5

### PR DESCRIPTION
**Pull request by loftlifter31**
Config files which came from other sources on github have been annotated with source. Config files without annotations are customizations of existing heads config files modified by me to the requirements of the board.

### CODE REVIEW

**Comment by tlaurion** [comment]
@loftlifter31  from #1765 
>Board config, Linux config coreboot config that I will be able to review comparing other boards of same or similar family, nothing what is HCL, iGPU, dGPU and other things that could prevent booting or have console output

So what is "non-booting" ? what is iGPU etc? what is HCL?
Please rpovide details not expecting me to work on this prior of understanding at least in theory what is "not working".

**Comment by loftlifter31** [comment]
@tlaurion GPU is Intel Iris Xe. I'm not sure what HCL is. Hardware compatibility list? Maybe the info you want is here? https://tech-docs.system76.com/models/galp5/README.html

Not booting in this case means black screen on power on. Video backlight comes on and power led changes from amber to green but nothing is displayed on screen. I suspect there may be an issue with the VBT based on a conversation with one of the System76 developers. Apparently the "parser" needs to match the VBT. I tried replacing the vbt.rom I had been using from the System76 github repository with the VBT extracted from the working firmware which shipped with the machine. Also tried using the data.vbt coreboot includes under src/mainboard/system76/tgl-u/variants/galp5/. Also tried commenting out the CONFIG_INTEL_GMA_VBT_FILE line to let coreboot use whatever it thinks is best. None of those solutions result in any video output.

**Comment by tlaurion** [comment]
@loftlifter31 are you under Heads matrix channel?

This is one of the subject where dynamic discussions would be way more effective then trying to fix your itch through PR.
Community page: https://osresearch.net/community/

Otherwise the reason why I pointed you to check HCL (yes hardware compatibility list) is that you could see that other platforms are really similar. For example you could basically borrow a librem similar to that hardware, and then start comparing configs and make it work.

As you saw with your own upstream discussions, you seem to come near the conclusion that using an old fork of coreboot won't work. So you could check history of modules/coreboot file, and then incororate system76 coreboot fork.

Then borrow librem coreboot config, linux config and then arrive to a booting system using coreboot libgfxinit to drive iGPU up to linux efifb driver and have something working probably really quick.

Reach on matrix channel and open a thread there, I can point you to things, and link those discussions here. 


Direct pointers:
- You will need libgfxinit, efifb and vbt yes. so next step is use their fork under modules/coreboot

**Comment by tlaurion** [comment]
Put as draft. Please #1774 as a base to force push commits here from git from command line.

**Comment by tlaurion** [comment]
Deprecated in favor of #1774. To propose superseeding PR, you will need to create a branch, not use master of your fork.
Closing.

**Pull request closed without merging**
