### PR TITLE
flash.sh: drop inhouse progress output on console when flashing with flashrom

### PR DESCRIPTION
**Pull request by tlaurion**
Flashrom dropped --progress output under 1.2.
flashrom 1.4 still has no --progress output.

---

Heads implemented in-house progress output as a workaround until fixed upstream.
That never happened.
This is still opened issue https://ticket.coreboot.org/issues/390
---

As per https://github.com/linuxboot/heads/pull/1753#discussion_r1725694439 @JonathonHall-Purism comment:
> What would you think about removing the progress bar? The dream would be to rework it (maybe doing it in flashrom itself, or at least providing a reliably-parseable progress output), but the current implementation is a huge pain, I don't feel it adds enough value to outweigh the pain. For comparison the read step takes a comparable amount of time and does not have a progress bar.

---

So here, we drop progress output and leave user in the dark while they erase/write the firmware internally when upgrading Heads.

### CODE REVIEW

**Comment by tlaurion** [comment]
@JonathonHall-Purism works as intended. Merge?

**Comment by JonathonHall-Purism** [comment]
:100: Let's merge, thank you @tlaurion 

I'm thrilled to see this go.  While it's not awesome to leave users with an indefinite wait, it is far better than sometimes freezing during a critical potentially-bricking operation, and this code was a nightmare to maintain.

**Comment by tlaurion** [comment]
> :100: Let's merge, thank you @tlaurion 
> 
> I'm thrilled to see this go.  While it's not awesome to leave users with an indefinite wait, it is far better than sometimes freezing during a critical potentially-bricking operation, and this code was a nightmare to maintain.

@JonathonHall-Purism please approve!

**Review by JonathonHall-Purism — APPROVED** [review]

**Comment by tlaurion** [comment]
Master flashrom output for 1.3 with e typing on keyboard in scary dark moment, in between flashrom stating it will do write erase operations prior of doing them.

**Pull request merged**
