### PR TITLE
nitropad-nx: use standard shutdown/reboot commands

### PR DESCRIPTION
**Pull request by macpijan**
This commit effectively reverts commits a1c13ff and 902866cc. There is no need for this special EC-based poweroff command. See more details in issue linked below.

Fixes: https://github.com/Dasharo/dasharo-issues/issues/711

Not actually tested on master yet, only on this branch and forward picked: https://github.com/Dasharo/heads/pull/11

Not sure why it was implemented (guessing EC update?). Maybe we will find out in this review.

### CODE REVIEW

**Comment by tlaurion** [comment]
> This commit effectively reverts commits [a1c13ff](https://github.com/linuxboot/heads/commit/a1c13ff13224fae4e367270b2b6c1069facd584f) and [902866c](https://github.com/linuxboot/heads/commit/902866cc296118a4f0f4d94f3a0d4684bb3bd757). There is no need for this special EC-based poweroff command. See more details in issue linked below.
> 
> Fixes: [Dasharo/dasharo-issues#711](https://github.com/Dasharo/dasharo-issues/issues/711)

Will let it build and happily test on my nv41 but should work out of the box.

> Not actually tested on master yet, only on this branch and forward picked: [Dasharo#11](https://github.com/Dasharo/heads/pull/11)
> 
> Not sure why it was implemented (guessing EC update?). Maybe we will find out in this review.

I guess it's an artifact of using proprietary EC, but I do not know the whole story nor was owning a nv41 back then.
@daringer please fill us in?

**Comment by macpijan** [comment]
> Although if somebody wants to overwrite the entire flash (not just the bios region) - rebooting will fail afterwards, right @macpijan ?

I am not aware of such interaction. @mkopec can you please confirm this?

**Comment by tlaurion** [comment]
> Yes, that's a "historic artifact" .... I'd suggest then also removing iotools as this is only needed here. Although if somebody wants to overwrite the entire flash (not just the bios region) - rebooting will fail afterwards, right @macpijan ? but under the line this shouldn't happen anyways, so removing both (iotools + shutdown-instead-of-reboot) should be fine



> Flashing the ME when it's not disabled may result in shutdown / reboot issues indeed, but it shouldn't matter as long as ME is disabled (by HMRFPO or any other method)

@daringer so this was not related to EC but ME. Restesting.

**Comment by tlaurion** [comment]
Reboot works. Inspecting cbmem

**Comment by tlaurion** [comment]
`cbmem --console ¦ grep '^ME' ` gives not output at all.

**Comment by tlaurion** [comment]
This circleci rom artifacts contains hotp-verification v1.5 not 1.6, inspecting.

**Comment by tlaurion** [comment]
@macpijan Please rebase on master.

Restesting this as https://github.com/tlaurion/heads/tree/Dasharo_nitropad-shutdown which is this commit on master.

**Comment by tlaurion** [comment]
> @macpijan Please rebase on master.
> 
> Retesting this as https://github.com/tlaurion/heads/tree/Dasharo_nitropad-shutdown which is this commit on master.

@macpijan nevermind. Merging this.

**Review by tlaurion — APPROVED** [review]
Tested https://app.circleci.com/pipelines/github/Dasharo/heads/122/workflows/7c0cdcf1-4a02-4ea1-9d98-28aef5d4209c/jobs/2117/artifacts all ok.

Suggested adding https://github.com/linuxboot/heads/commit/c7a5fbd66fefc5853ec8e9128bf5d3304b45e85f but unrelated. Merging

**Comment by tlaurion** [comment]
For prosperity, it seems that ME was shipped activated in the past see https://github.com/Nitrokey/heads/releases/tag/v2.4.1

**Comment by tlaurion** [comment]
@macpijan other boards include it under master. Can you generalize and push commit sedding all the boards please?

**Pull request merged**
