### PR TITLE
Makefile: Support passing environment variables through make--and use…

### PR DESCRIPTION
**Pull request by daym**
… it to support host compilers that use environment variables CPATH etc. See Issue #609.

### CODE REVIEW

**Comment by daym** [comment]
TODO: Test via:

```
cd heads
make BOARD=YourBoard real.clean
rm -rf crossgcc
make BOARD=YourBoard
```

on fedora-30.

**Comment by daym** [comment]
With `make BOARD=qemu-linuxboot` on Guix I get:

```
gawk: fatal: cannot use gawk builtin `namespace' as variable
```

in libgpg-error.

Gawk used is v5.0.1.

See also https://stackoverflow.com/questions/55664467/gawk-error-when-compiling-libgpg-error-in-crossdev-armv7a-environment

**Comment by tlaurion** [comment]
@daym please see https://github.com/osresearch/heads/pull/714

**Comment by tlaurion** [comment]
@daym : Fixes were merged upstream. Please retest!

**Comment by daym** [comment]
Rebased to your current master.

**Comment by tlaurion** [comment]
@daym  Testing this locally

**Comment by tlaurion** [comment]
@daym https://github.com/osresearch/heads/issues/609#issuecomment-635978789

**Comment by tlaurion** [comment]
@daym : You can see the results of failed builds at each additional commit by clicking the check details, then the details which will bring you to CircleCI where you can see errors of the current build.

This is a long process, since each PR builds the whole cross-gcc-make toolchain and then the boards defined there. The https://github.com/osresearch/heads/commit/90216068f438a2a60dc01276b141f44bb20189d6 commit resulted in [this failed build](https://circleci.com/gh/daym/heads/2?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by tlaurion** [comment]
@daym Would love to chat with you. You seem to have expertise i'm looking for and we could collaborate in fixing hte build system.

Want to contact me from methods defined at insurgo.ca/#contact ?

**Comment by tlaurion** [comment]
@daym : the discussion could also happen under #609.

**Comment by tlaurion** [comment]
I think this is done, where nix is used now as #1661 is merged

**Pull request closed without merging**
