### PR TITLE
4.22.01 fhd patch merged upstream (4.24) + bump all 4.19 boards to 4.22.01

### LINKED ISSUE #1603: OS Reboot with i915 Enabled Disables Internal Display - x230 fhd_edp (a.gain)
### A. Provide Hardware Details

**1. What board are you using (see list of boards [here](https://github.com/eganonoa/heads/tree/master/boards))?**
[x230-maximized-fhd_edp](https://github.com/linuxboot/heads/tree/master/boards/x230-maximized-fhd_edp)
 
Mod Kit:  a.gain X220_X230 FHD RevA1.0

**2. Does your computer have a dGPU or is it iGPU-only?**
- [x] iGPU-only

**3. Who installed Heads on this computer?**
- [x] Self-installed

**4. What PGP key is being used?**
- [x] Yubikey

**5. Are you using the PGP key to provide HOTP verification?**
- [x] No

### B. Identify how the board was flashed

**1. Is this problem related to updating heads or flashing it for the first time?**
- [x] Updating heads

**2. If the problem is related to an update, how did you attempt to apply the update?**
- [x] Using the Heads GUI

**3. How was Heads initially flashed**
- [x] External flashing

**4. Was the board flashed with a maximized or non-maximized/legacy rom?**
- [x] Maximized

**5. If Heads was externally flashed, was IFD unlocked?**
- [x] Yes

### C. Identify the rom related to this bug report

**1. Did you download or build the rom at issue in this bug report?**
- [x] I downloaded it

**2. If you downloaded your rom, where did you get it from?**
- [x] Heads CircleCi

*Please provide the release number or otherwise identify the rom downloaded*
heads-x230-maximized-fhd_edp-v0.2.0-2022-g5bff519

## Problem

**Describe the bug**
After updating from an older version (early Feb 2023 I think) of Heads rebooting from OS doesn't seem to work. All the systems lights turn off (USB still blinks if plugged in) but the system hangs in that state appearing to be powered off. Holding the power button leads to the "pop" sound as the system is forced shutdown. I experienced this in both the latest Fedora and QubesOS.

**To Reproduce**
1. Boot OS
2. Login
3. Reboot device

**Expected behavior**
Successful reboot of system

**Additional context**
Rebooting from heads itself works without issue. Non-fhd_edp  x230 appears to works without issue.
heads-x230-maximized-fhd_edp-v0.2.0-1978-gc9e067c the oldest version I could download also has the issue

## Additional Tests
- [x] Alternative heads versions
  - [x] c4b964c : Functional
  - [x] 5c7148f : Functional
  - [x] 6300dd1 : Functional
  - [x] 1f39d16 :  Failed reboot
  - [x]  heads-x230-maximized-fhd_edp-v0.2.0-1978-gc9e067c : Failed reboot
  - [x]  heads-x230-maximized-fhd_edp-v0.2.0-1978-gc9e067c with stock vbt : Failed reboot
  - [x] non-fhd board
- [x] Test Coreboot with SeaBIOS payload

### PR DESCRIPTION
**Pull request by tlaurion**
Revisiting 4.22 coreboot bump with fhd patch (superseeds and replaces #1524), Might fix #1603)

    - patches/coreboot-4.22.01/0001-x230-fhd-variant.patch created per
      - git fetch https://review.coreboot.org/coreboot refs/changes/50/28950/27 && git format-patch -1 --stdout FETCH_HEAD > ~/heads/patches/coreboot-4.22.01/0001-x230-fhd-variant.patch
    - all boards configs bumped with:
      - sed 's/4.19/4.22.01/g' boards/*/*.config -i
      - grep -Rn 4.22 boards/ | awk -F "/" {'print $2'}| while read line; do make BOARD=$line coreboot.save_in_oldconfig_format_in_place ; done
      - sed 's/4.19/4.22.01/g' .circleci/config.yml -i
    - CircleCI caches updated
    - modules/coreboot: remove 4.19 references
    - All 4.19 boards switched to TCG event log format which segfaults `cbmem -L` https://github.com/linuxboot/heads/issues/1608#issuecomment-1953036042
      - Note that Purism boards already switched to TCG format where https://github.com/linuxboot/heads/pull/1609 doesn't fix anything (coreboot custom event log format is broken since 4.21
        - **More details under https://github.com/linuxboot/heads/issues/1608 which isn't blocking this PR** 

Testing report at https://github.com/linuxboot/heads/pull/1604#issuecomment-1953128002

----

4.22 didn't include the patchset in time as https://github.com/linuxboot/heads/issues/1523 related.
~Hopefully this is the last time we pick a patchset. Please board owners, report your edp/fhd kit (PRECISELY) and passing/failing results under https://review.coreboot.org/c/coreboot/+/28950~ EDIT: https://review.coreboot.org/coreboot refs/changes/50/28950/27 was merged.

### CODE REVIEW

**Comment by tlaurion** [comment]
Testing https://output.circle-artifacts.com/output/job/921af8c2-40cd-4b91-886b-f48c99d8749e/artifacts/0/build/x86/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-2023-g1a6aacb.zip which passed to 4.22. 

Will update this comment.

**Comment by JonathonHall-Purism** [comment]
(realize it's WIP but took a quick look :slightly_smiling_face: ) Do any boards remain on 4.19 after this change?  If not, IMO we should remove it from modules/coreboot.

**Comment by pcm720** [comment]
Works perfectly on eDP 4.0-modded X230 with 1440p display.

**Comment by tlaurion** [comment]
> Works perfectly on eDP 4.0-modded X230 with 1440p display. "Unknown TPM log specification" doesn't prevent TPM from unlocking encrypted root partition.

Cannot replicate with qemu-coreboot-whitail-tpm1/tpm2 boards, this is weird.

**Comment by JonathonHall-Purism** [comment]
@tlaurion I'm working on PureBoot 29 release candidates now (updating coreboot to 4.22.01 there as well) and I get something similar with cbmem -L, but I'm not sure it's exactly the same.

It does appear to show the TPM log correctly, but then it shows a huge garbage entry and crashes.  Sealing still works because the correct part of the log is interpreted correctly by tpmr.  It looks like tpmr is wandering off into uninitialized space following the TPM log (but haven't confirmed that).

Is that similar to what you see?

Next steps IMO would be to build cbmem in the host OS see if it's the same (see if it's specific to the Heads build/environment or not, since it would surprise me if it was doing this across the board upstream), then probably bisect coreboot and/or cbmem based on that result.

**Comment by tlaurion** [comment]
Checking at history of cbmem https://github.com/coreboot/coreboot/commits/7201602a18b63fc5236f025d22dc726637866cb6/util/cbmem/cbmem.c, it seems something went wrong either at https://github.com/coreboot/coreboot/commit/6da62684dee6b2df49fa1d51e74e14c181c9349e when supporting tpm1.2/tpm2.0 format or https://github.com/coreboot/coreboot/commit/fc2f304f062bc51cf51ad999caf13a6acc64a1b3 when attempting to standardize c99 arrays.


> @tlaurion I'm working on PureBoot 29 release candidates now (updating coreboot to 4.22.01 there as well) and I get something similar with cbmem -L, but I'm not sure it's exactly the same.

On x230 I only get "Unknown TPM log specification:" (note the ':' and nothing else) at 
https://github.com/coreboot/coreboot/blob/fc2f304f062bc51cf51ad999caf13a6acc64a1b3/util/cbmem/cbmem.c#L1059-L1061


> 
> It does appear to show the TPM log correctly, but then it shows a huge garbage entry and crashes. Sealing still works because the correct part of the log is interpreted correctly by tpmr. It looks like cbmem is wandering off into uninitialized space following the TPM log (but haven't confirmed that).

> 
> Is that similar to what you see?

No. I get this when I switch the TPM log format to 1.2 though, not when using coreboot custom format that we currently use.

> 
> Next steps IMO would be to build cbmem in the host OS see if it's the same (see if it's specific to the Heads build/environment or not, since it would surprise me if it was doing this across the board upstream), then probably bisect coreboot and/or cbmem based on that result.

Well, TBH I'm not sure a lot of other use so much measured boot outside of Heads @JonathonHall-Purism ?
This shows its not tested a lot, or as you said, since cbmem is built by musl-cross-make, that might as well be an undesired artifact of those?

**Comment by tlaurion** [comment]
@JonathonHall-Purism tested bumping musl-cross-make to latest avail [commit](https://github.com/richfelker/musl-cross-make/commit/fe915821b652a7fa37b34a596f47d8e20bc72338)  but same error on x230-maximized and clean built: "Unknown TPM log specification:" 

https://github.com/tlaurion/heads/tree/422_fhd_newer-musl

**Comment by tlaurion** [comment]
@JonathonHall-Purism 

I took the time to use rom produced here (4.22.01 tag release codebase built with measured boot and coreboot custom event log format) and test cbmem built on top of ubuntu 23.10/debian trixie.

Interestingly enough:
- `sudo ~/Downloada/coreboot-4.22.01/util/cbmem/cbmem -L` :  `Unknown TPM log specification:` : FAIL
- `sudo ~/Downloada/coreboot-4.19/util/cbmem/cbmem -L` : `coreboot TPM log: [...]` : OK


So now, let's test cbmem behavior in between those release versions:
- `sudo ~/Downloada/coreboot-4.21/util/cbmem/cbmem -L` :  `Unknown TPM log specification:` : FAIL
- `sudo ~/Downloada/coreboot-4.20.1/util/cbmem/cbmem -L` : `coreboot TPM log: [...]` : OK

**So `cbmem -L` is broken since somwhere between 4.20.1 and 4.21.**

**Comment by tlaurion** [comment]
Thanks yo you all, edp/fhd was merged upstream.

**Comment by tlaurion** [comment]
Testing FHD+4.23 coreboot is under https://github.com/tlaurion/heads/tree/pre423-edp_fhd_in-tpm_tcg_event_log-CircleCi_coreboot_cache_fixed

As of now, the branch is just to show that cbmem -L fails (just as here) but for fixes to be made upstream as reported at https://github.com/linuxboot/heads/pull/1609#issuecomment-1944461330

**Comment by tlaurion** [comment]
Updated to match coreboot merged https://review.coreboot.org/c/coreboot/+/28950. Might need manual fix (since other things changed for 4.23)

**Comment by tlaurion** [comment]
Logs for segfaulting TCG event log cbmem -L output under https://github.com/linuxboot/heads/issues/1608#issuecomment-1953036042

**Comment by tlaurion** [comment]
@pcm720 can you confirm upstream merged+modified(minimal: only filename changes) edp/fhd patchset works as expected here? Should.

**Comment by tlaurion** [comment]
https://github.com/linuxboot/heads/issues/1603#issuecomment-1953074868 "reboot issue" might not be fixed by this and as of today, is outside of my understanding.

**Comment by tlaurion** [comment]
Tested:

- [ ] w530-hotp-maximized (main station)
- [ ] x230-maximized (testing station)

Will edit with request for testing of boards affected after testing and not seeing regression. 
As of now, hotp/TPM DUK+suspend+resume works as expected.

**Comment by tlaurion** [comment]
Testing needed, everyone!

**Comment by tlaurion** [comment]
Untested boards will move to UNTESTED.
UNTESTED boards that were untested prior of this PR will go to UNMAINTAINED in future commit prior of merging.

**Comment by natterangell** [comment]
t420-hotp-maximized tested and works!On Feb 21, 2024, at 22:30, Thierry Laurion ***@***.***> wrote:﻿
Untested boards will move to UNTESTED.
UNTESTED boards that were untested prior of this PR will go to UNMAINTAINED in future commit prior of merging.

**Comment by d-wid** [comment]
I'll get to it next Wednesday or, if you don't mind

**Comment by JonathonHall-Purism** [comment]
> I'll get to it next Wednesday or, if you don't mind

tlaurion is away until March 20th, so no rush :+1:

**Comment by tlaurion** [comment]
> > I'll get to it next Wednesday or, if you don't mind
> 
> tlaurion is away until March 20th, so no rush :+1:

@d-wid @JonathonHall-Purism it was intentional to push for testing before leaving on my side. Last time I asked for testing, it took more then 3weeks to get the results.

So @d-wid and others: please have your testing reports before march 20th. Happy testing!

**Comment by srgrint** [comment]
Have tested heads-x220-maximized-v0.2.0-2027-g6b61f61.rom  Seems to work fine.

**Comment by gaspar-ilom** [comment]
I have regression tested W541 (heads-w541-hotp-maximized-v0.2.0-2027-g6b61f61.rom). No findings. You may mark it as tested.

**Comment by srgrint** [comment]
Have also tested t440p - also seems to work fine.

**Comment by srgrint** [comment]
Tested on my intel graphics T430.  Seems to work fine.

**Comment by d-wid** [comment]
Seems to work fine on the HP Z220 too.

**Comment by tlaurion** [comment]
Thanks to all testing reports per https://github.com/linuxboot/heads/pull/1604#issuecomment-1953128002, last call for testing for :
- [ ] t430-dgpu (xx30): @weyounsix (t430-dgpu)
- [ ] [t520](https://doc.coreboot.org/mainboard/lenovo/t520.html) (xx30): NOBODY
- [ ] [t530](https://doc.coreboot.org/mainboard/lenovo/t530.html) (xx30): @3hhh
- [ ] [w530-dgpu](https://doc.coreboot.org/mainboard/lenovo/w530.html) (xx30): @weyounsix (dGPU: w530-k2000m) @jnscmns (dGPU K1000M) @computer-user123 (w530 / & w530 k2000 : prefers iGPU)
- [ ] X230i (x230): @natterangell
- [ ] [ASUS P8Z77 M PRO (Ivy bridge)](https://doc.coreboot.org/mainboard/asus/p8z77-m_pro.html): @ThePlexus 


Some boards will go to UNTESTED, and current UNTESTED boards will go UNMAINTAINTED.

**Comment by natterangell** [comment]
X230i tested and works 👍🏻

**Comment by tlaurion** [comment]
Rebased on master and moved boards from boards/UNTESTED_* to unmaintained_boards/UNMAINTAINED_* per added Makefile helper, removed them from CircleCI.

If there is interest for those boards, they will need to be brought back with proper testing and board owner willingness to maintain/at least test when needed:

See [9fcd5f8](https://github.com/linuxboot/heads/pull/1604/commits/9fcd5f8fe488389734423e8d15606b433d675c10) related changes.

@JonathonHall-Purism : merge?

**Review by JonathonHall-Purism — APPROVED** [review]

**Comment by JonathonHall-Purism** [comment]
Thanks @tlaurion , yes looks good to me for merge :+1:

**Pull request merged**
