### PR TITLE
coreboot patches: replaced lib/jpeg patches for heap increase and alloc failure with upstreamed merged ones

### PR DESCRIPTION
**Pull request by tlaurion**
Upstream merged lib/jpeg chosen fixes, more elegant then increasing the HEAP_SIZE:
- https://review.coreboot.org/c/coreboot/+/83895/3
- https://review.coreboot.org/c/coreboot/+/83894/2

This replaces pending patches (Dasharo fork not needing HEAP_SIZE changes in configs in master since based on coreboot prior of https://review.coreboot.org/c/coreboot/+/78271 which introduced wuff for jpeg parser)

----

Repro:
```
rm patches/coreboot-24.02.01/0001* patches/coreboot-24.02.01/0002*
git fetch https://review.coreboot.org/coreboot refs/changes/94/83894/2 && git format-patch -1 --stdout FETCH_HEAD > patches/coreboot-24.02.01/0001-vc_wuffs-upgrade-to-Wuffs_0.4.0-alpha.8.patch
git fetch https://review.coreboot.org/coreboot refs/changes/95/83895/3 && git format-patch -1 --stdout FETCH_HEAD > patches/coreboot-24.02.01/0002-lib_jpeg-avoidcalling-malloc-and-free.patch
sed -i 's/CONFIG_HEAP_SIZE=0x400000/CONFIG_HEAP_SIZE=0x100000/g' config/coreboot-*
```

@JonathonHall-Purism (Purism fork needs the change too)

Tested working under qemu.

### CODE REVIEW

**Comment by JonathonHall-Purism** [comment]
@tlaurion Please cherry-pick this change to coreboot-purism: https://github.com/linuxboot/heads/commit/d67ffae2b1fcf6a1c24b019c8ab0ffa9319b823f

This updates the Purism coreboot with the JPEG decoder improvements, which is needed to revert their coreboot Kconfigs (already done in the PR).

I'll test once we get a CI build.

**Comment by tlaurion** [comment]
@JonathonHall-Purism sorry for the delay: roms built for [3a07b09](https://github.com/linuxboot/heads/pull/1795/commits/3a07b09d1b9c9d33da48acbc1c7787639ef49a7b)

**Comment by tlaurion** [comment]
@JonathonHall-Purism ping :)

**Review by JonathonHall-Purism — APPROVED** [review]
Tested Librem 14, works.  LGTM :+1:

**Comment by tlaurion** [comment]
Review OptiPlex

**Pull request merged**
