### PR TITLE
coreboot 24.02.04: Fix top down allocation for platforms up to Haswell

### LINKED ISSUE #1740: Regression: Some peripherals are not discovered since 4.22.01 -> 24.02.04 Coreboot Version bump (upstream: bogus top down allocator)
### A. Provide Hardware Details

1. What board are you using? (Choose from the list of boards [here](https://github.com/eganonoa/heads/tree/master/boards))
Lenovo Thinkpad T430

3. Does your computer have a dGPU or is it iGPU-only?
    - [x] dGPU (Distinct GPU other then internal GPU)
    - [ ] iGPU-only (Internal GPU, normally Intel GPU)

4. Who installed Heads on this computer?
    - [ ] Insurgo (Issues to be reported at https://github.com/linuxboot/heads/issues)
    - [ ] Nitrokey (Issues to be reported at https://github.com/Nitrokey/heads/issues)
    - [ ] Purism (Issues to be reported at https://source.puri.sm/firmware/pureboot/-/issues)
    - [ ] Novacustom (Issues to be reported at https://github.com/Dasharo/dasharo-issues)
    - [ ] HardnenedVault (Issues to be reported at https://github.com/hardenedvault/vaultboot/issues)
    - [ ] Other provider
    - [x] Self-installed

5. What PGP key is being used?
    - [ ] Librem Key (Nitrokey Pro 2 rebranded)
    - [ ] Nitrokey Pro
    - [ ] Nitrokey Pro 2
    - [x] Nitrokey 3 NFC
    - [ ] Nitrokey 3 NFC Mini
    - [ ] Nitrokey Storage
    - [ ] Nitrokey Storage 2
    - [ ] Yubikey
    - [ ] Other

6. Are you using the PGP key to provide HOTP verification?
    - [x] Yes
    - [ ] No
    - [ ] I don't know

### B. Identify how the board was flashed

1. Is this problem related to updating heads or flashing it for the first time?
    - [ ] First-time flash
    - [x] Updating heads 

2. If the problem is related to an update, how did you attempt to apply the update?
    - [x] Using the Heads menus
    - [ ] Flashrom via the Recovery Shell
    - [ ] External flashing

3. How was Heads initially flashed?
    - [x] External flashing
    - [ ] Internal-only / 1vyprep+1vyrain / skulls
    - [ ] Don't know

4. Was the board flashed with a maximized or non-maximized/legacy rom?
    - [x] Maximized
    - [ ] Non-maximized / legacy
    - [ ] I don't know

5. If Heads was externally flashed, was IFD unlocked?
    - [x] Yes
    - [ ] No
    - [ ] Don't know

### C. Identify the rom related to this bug report
V0.2.0-2254-g27d09d4
1. Did you download or build the rom at issue in this bug report?
    - [ ] I downloaded it
    - [x] I built it

2. If you downloaded your rom, where did you get it from?
    - [ ] Heads CircleCi
    - [ ] Purism
    - [ ] Nitrokey
    - [ ] Dasharo DTS (Novacustom)
    - [ ] Somewhere else (please identify)

    *Please provide the release number or otherwise identify the rom downloaded*

3. If you built your rom, which repository:branch did you use?
    - [x] Heads:Master
    - [ ] Other (please identify)

4. What version of coreboot did you use in building?
{ You can find this information from github commit ID or once flashed, by giving the complete version from Sytem Information under Options --> menu}

5. In building the rom, where did you get the blobs?
    - [ ] No blobs required
    - [ ] Provided by the company that installed Heads on the device
    - [x] Extracted from a backup rom taken from this device(MAC-Adress in gbe.bin)
    - [ ] Extracted from another backup rom taken from another device (please identify the board model)
    - [x] Extracted from the online bios using the automated tools provided in Heads(me.bin)
    - [ ] I don't know

## Please describe the problem

**Describe the bug**

The two USB-Ports close to the Power-Button don't work after heads update. (On two devices, t430-maximized with a clean checkout and t430-hotp-maximized from dirty local repository)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by tlaurion**
- Superseeds #1742 : include https://review.coreboot.org/c/coreboot/+/80207
- Fixes #1740 

---

tested on x230: webcam and m.2 msata drives reappeared.

---

@macpijan : might want to investigate this and turn that on on nv41/ns50 and others.
@JonathonHall-Purism seems already in for librems?
@Oessel: please retest on t430

### CODE REVIEW

**Comment by tlaurion** [comment]
@i-c-o-n: not sure if should be merged like this though, or if all boards  touched by file changes here should be tested by board owners? Thoughts?

**Comment by Oessel** [comment]
It works on t430!

**Comment by JonathonHall-Purism** [comment]
> @JonathonHall-Purism seems already in for librems?

Not needed for Librems, they don't use any of these chipsets.

**Comment by tlaurion** [comment]
@JonathonHall-Purism so e ady for merge? Better then what is on master.

**Comment by JonathonHall-Purism** [comment]
If it works for those boards I'm fine with it :+1:

**Comment by tlaurion** [comment]
[Should be improvement over state of master](https://matrix.to/#/!EhaGFZyYcbyhdSgStq:matrix.org/$0DgvLdSm09wa8-hmV-FO-8la03h3gsQrVO6n7fwxuO8?via=matrix.org&via=sibnsk.net&via=nope.chat). 

Merging

**Pull request merged**
