### PR TITLE
kgpe-d16: add nvme support under linux kernel configs - PR superseeding #1727

### PR DESCRIPTION
**Pull request by tlaurion**
Signed commit @arhabd commit (`git --signoff -amend`) and rebased on master.

@arhabd please test rom from CircleCI on top of this branch and if successful, we can merge. Reviewed your changes on top of master here and used helper to make sure nothing new was introduced by using

`docker run -e DISPLAY=$DISPLAY --network host --rm -ti -v $(pwd):$(pwd) -w $(pwd) tlaurion/heads-dev-env:latest -- make BOARD=UNMAINTAINED_kgpe-d16_workstation linux.modify_and_save_oldconfig_in_place`

### CODE REVIEW

**Comment by tlaurion** [comment]
@arhabd [211aeab](https://github.com/linuxboot/heads/pull/1738/commits/211aeabf3523615f4637abfa77a8ae3cc759c92c) generalizes the changes to other kgpe-d16 linux configs: no reason not adding it for all and also ease maintainership. Repro under commit log.


@arhabd please approve PR and will merge once builds successful by CircleCI.

**Comment by tlaurion** [comment]
@arhabd Please take note of https://github.com/linuxboot/heads/blob/master/CONTRIBUTING.md for future contributions.

Thanks for this one!

**Review by arhabd — APPROVED** [review]
flashed 211aeab from circleci and booted fine and i have the option to set /nvme0n1 as my boot device

**Comment by tlaurion** [comment]
Sorry, name of this PR is just wrong. It's related to kgpe-d16, not system clock, at all. Renaming.

**Pull request merged**
