### PR TITLE
Enable vboot on Lenovo devices for measured boot

### PR DESCRIPTION
**Pull request by PatrickRudolph**

### CODE REVIEW

**Comment by tlaurion** [comment]
A quick recap on the status of this PR.

From commit logs, **general concerns in bold**

- https://github.com/osresearch/heads/pull/709/commits/8f4e76cb8de7e744e821f8c192b02dae12ad1832
> This commit does only apply the basic requirement for vboot targets.
> It does not adapt any board configurations and also disables the use of
> the crosstoolchain for coreboot. Therfore it shouldn't be merged with
> the master branch at the current state.

- https://github.com/osresearch/heads/pull/709/commits/e5ecc7fa2032f3e2ba3ee0edaa4683b566537de3
> boards: add vboot Sandy Bridge targets
> 
> added targets:
> - vboot-x220 (Lenovo Thinkpad X220)
> - vboot-t420 (Lenovo Thinkpad T420)
> 
> **Move linux-x230.config to linux-thinkpad.config**, so can be used
> as generic linux kernel for all Thinkpads.

- https://github.com/osresearch/heads/pull/709/commits/4868694a6b072b7fd138d8bb476cbe7f774c4ea9

> 
>  boards: add vboot Ivy Bridge targets
> 
> added targets:
> - vboot-x230 (Lenovo Thinkpad X230)
> - vboot-x230-me
> - vboot-t430 (Lenovo Thinkpad T430)
> - vboot-t430-me
> - vboot-t530 (Lenovo Thinkpad T530)
> - vboot-t530-me
> - vboot-w530 (Lenovo Thinkpad W530)
> - vboot-w530-me
> 
> All targets with the `-me` suffix uses the full sized Intel ME
> without shrinking it.
> 
> **Warning:**
> **the heads payload is currently 247 KiB too big for the targets**
> **with the full sized ME.**
> **(Tested on a X230 using the vboot-x230-me target)**

- https://github.com/osresearch/heads/pull/709/commits/fe1f1ee1e8ac3cf7f50deda84cbd45f8a45ef3dc

>  bin: add lenovo_extract.sh script
> 
> Add a generic bash script to **extract necessary blobs from**
> **Lenovo Firmware Dumps**.
> 

- https://github.com/osresearch/heads/pull/709/commits/f57fd22c9bc890e2e68688be354327ed7d8390ef

>  bin/lenovo_extract.sh: Verify target board prefix
> 
> Verify if the target board prefix matches, instead of the full name.
> 

- https://github.com/osresearch/heads/pull/709/commits/8824eba378d5a1c1ed95b1aad527c537d557e4fc
> modules/coreboot: adapt toolchain target file

**Comment by PatrickRudolph** [comment]
Please comment inline what should be fixed. Marking sentences bold doesn't help anybody.

The first commit could be postponed until the next coreboot release, which will likely be released in two weeks.
That heads is to big for a non stripped ME is known and out of scope of this commit.
Extracting blobs is required as it contains the MAC of the GbE.

**Comment by tlaurion** [comment]
Testing.

**Comment by tlaurion** [comment]
@PatrickRudolph : Some notes.

```
user@x230-vboot:~/heads$ ./bin/lenovo_extract.sh -f /home/user/QubesIncoming/bottom.rom
user@x230-vboot:~/heads$ ls blobs/x230/
ifd.bin  me.bin
user@x230-vboot:~/heads$ make BOARD=vboot-x230
tail /home/user/heads/build/log/coreboot.log
-----
    HOSTCC     cbfstool/2sha256.o
    HOSTCC     cbfstool/2sha512.o
    HOSTCC     cbfstool/linux_trampoline.o
    HOSTCC     cbfstool/cbfs-payload-linux.o
    HOSTCC     cbfstool/compress.o
    HOSTCC     cbfstool/lz4.o
    HOSTCC     cbfstool/lz4hc.o
    HOSTCC     cbfstool/lz4frame.o
    HOSTCC     cbfstool/xxhash.o
    HOSTCC     cbfstool/lz4_wrapper.o
    HOSTCC     cbfstool/lzma.o
    HOSTCC     cbfstool/LzFind.o
    HOSTCC     cbfstool/LzmaDec.o
    HOSTCC     cbfstool/LzmaEnc.o
    HOSTCC     cbfstool/ifittool.o
    HOSTCC     cbfstool/fit.o
    Compile IFDTOOL
make[1]: *** No rule to make target '../../blobs/x230/ifd-minimal_me.bin', needed by 'add_intel_firmware'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/user/heads/build/coreboot-4.11'
make: *** [Makefile:382: /home/user/heads/build/coreboot-4.11/vboot-x230/.build] Error 1

```

**Comment by tlaurion** [comment]
@PatrickRudolph :
Note below error at final call of ifdtool and "Error while writing: Success"



Debian-10 output:
```
user@x230-vboot:~/heads$ ./bin/lenovo_extract.sh -f /home/user/QubesIncoming/PrivacyBeast-Certified-deploy/bottom.rom -t x230 
firmware rom: /home/user/QubesIncoming/PrivacyBeast-Certified-deploy/bottom.rom
me_cleaner: /home/user/heads/build/coreboot-4.11/util/me_cleaner/me_cleaner.py
ifdtool: /home/user/heads/build/coreboot-4.11/util/ifdtool/ifdtool
File /tmp/tmp.Z4cukaoa1n is 8388608 bytes
Setting the AltMeDisable to disable Intel ME...
Writing new image to /tmp/tmp.Z4cukaoa1n.new
File /tmp/tmp.Z4cukaoa1n is 8388608 bytes
  Flash Region 0 (Flash Descriptor): 00000000 - 00000fff 
  Flash Region 1 (BIOS): 00500000 - 00bfffff 
  Error while writing: Success
  Flash Region 2 (Intel ME): 00003000 - 004fffff 
  Flash Region 3 (GbE): 00001000 - 00002fff 
  Flash Region 4 (Platform Data): 00fff000 - 00000fff (unused)
/home/user/heads
ME/TXE image detected
Found FPT header at 0x10
Found 23 partition(s)
Found FTPR header: FTPR partition spans from 0x180000 to 0x24a000
ME/TXE firmware version 8.0.12.1498
Public key match: Intel ME, firmware versions 7.x.x.x, 8.x.x.x
Reading partitions list...
 ???? (0x000003c0 - 0x000000400, 0x00000040 total bytes): removed
 FOVD (0x00000400 - 0x000001000, 0x00000c00 total bytes): removed
 MDES (0x00001000 - 0x000002000, 0x00001000 total bytes): removed
 FCRS (0x00002000 - 0x000003000, 0x00001000 total bytes): removed
 EFFS (0x00003000 - 0x0000df000, 0x000dc000 total bytes): removed
 BIAL (NVRAM partition, no data, 0x0000add0 total bytes): nothing to remove
 BIEL (NVRAM partition, no data, 0x00003000 total bytes): nothing to remove
 BIIS (NVRAM partition, no data, 0x00036000 total bytes): nothing to remove
 NVCL (NVRAM partition, no data, 0x00010511 total bytes): nothing to remove
 NVCM (NVRAM partition, no data, 0x0000493e total bytes): nothing to remove
 NVCP (NVRAM partition, no data, 0x0000a553 total bytes): nothing to remove
 NVJC (NVRAM partition, no data, 0x00005000 total bytes): nothing to remove
 NVKR (NVRAM partition, no data, 0x0001151c total bytes): nothing to remove
 NVOS (NVRAM partition, no data, 0x0003429d total bytes): nothing to remove
 NVSH (NVRAM partition, no data, 0x00007609 total bytes): nothing to remove
 NVTD (NVRAM partition, no data, 0x00001eac total bytes): nothing to remove
 PLDM (NVRAM partition, no data, 0x0000a000 total bytes): nothing to remove
 GLUT (0x000df000 - 0x0000e3000, 0x00004000 total bytes): removed
 LOCL (0x000e3000 - 0x0000e7000, 0x00004000 total bytes): removed
 WCOD (0x000e7000 - 0x000140000, 0x00059000 total bytes): removed
 MDMV (0x00140000 - 0x000180000, 0x00040000 total bytes): removed
 FTPR (0x00180000 - 0x00024a000, 0x000ca000 total bytes): NOT removed
 NFTP (0x0024a000 - 0x0004a4000, 0x0025a000 total bytes): removed
Removing partition entries in FPT...
Removing EFFS presence flag...
Correcting checksum (0xfa)...
Reading FTPR modules list...
 UPDATE           (LZMA   , 0x1cb8ef - 0x1cbaad       ): removed
 ROMP             (Huffman, fragmented data, ~2 KiB   ): NOT removed, essential
 BUP              (Huffman, fragmented data, ~54 KiB  ): NOT removed, essential
 KERNEL           (Huffman, fragmented data, ~135 KiB ): removed
 POLICY           (Huffman, fragmented data, ~89 KiB  ): removed
 HOSTCOMM         (LZMA   , 0x1cbaad - 0x1d27c7       ): removed
 RSA              (LZMA   , 0x1d27c7 - 0x1d7a2e       ): removed
 CLS              (LZMA   , 0x1d7a2e - 0x1dd170       ): removed
 TDT              (LZMA   , 0x1dd170 - 0x1e3854       ): removed
 FTCS             (Huffman, fragmented data, ~18 KiB  ): removed
 ClsPriv          (LZMA   , 0x1e3854 - 0x1e3c34       ): removed
 SESSMGR          (LZMA   , 0x1e3c34 - 0x1f2584       ): removed
Relocating FTPR from 0x180000 - 0x24a000 to 0xcc0 - 0xcacc0...
 Adjusting FPT entry...
 Adjusting LUT start offset...
 Adjusting Huffman start offset...
 Adjusting chunks offsets...
 Moving data...
The ME minimum size should be 98304 bytes (0x18000 bytes)
Truncating file at 0x18000...
Checking the FTPR RSA signature... VALID
Done! Good luck!
File /tmp/tmp.Z4cukaoa1n is 8388608 bytes
DANGER: Region Intel ME is shrinking.
    The region will be truncated to fit.
    This may result in an unusable image.
Copy Descriptor 0 (Flash Descriptor) (4096 bytes)
   from 00000000+00000000:00000fff (      4096)
     to 00000000+00000000:00000fff (      4096)
Copy Descriptor 1 (BIOS) (7340032 bytes)
   from 00500000+00000000:00bfffff (   7340032)
     to 00020000+000e0000:007fffff (   8257536)
./bin/lenovo_extract.sh: line 120: 16587 Segmentation fault      $IFDTOOL -n "$TOP/fmaps/${SIZE}_minimal_me.layout" "$bioscopy"
```

**Comment by PatrickRudolph** [comment]
Oh yes good point. That script requires patches on top coreboot 4.11 that are merged into the next release.

**Comment by tlaurion** [comment]
@PatrickRudolph : What intereresst us from minimal_me (standard vboot-* platforms) may be the usage and adaptation of:

- [me_cleaner producing the ifd](https://github.com/corna/me_cleaner/wiki/External-flashing#neutralize-and-shrink-intel-me-useful-only-for-coreboot)
- Keeping Gbe in extraction step (else no ethernet, #700 )

**Comment by PatrickRudolph** [comment]
It might be possible to generate the GBE and fill it with a random MAC.
As me_cleaner is already able to handle most of the required functions adding a GBE extractor might be the easiest solution.

**Comment by tlaurion** [comment]
@PatrickRudolph : I've tested #721. Results there. Let me know if something newer needs to be tested or if same results would be expected from PCRs.

**Comment by tlaurion** [comment]
@MrChromebox Heads and coreboot don't use the same PCRs.
I think [Heads](https://github.com/osresearch/heads-wiki/blob/master/Keys.md#tpm-pcrs) should match coreboot PCRs for newer releases

**Comment by MrChromebox** [comment]
@tlaurion I'm unclear what you're proposing. Also, coreboot's use of the PCRs will vary depending on if vboot is used or not.

**Comment by tlaurion** [comment]
OK let me clarify this and Patrick should clarify.

9elements work here is to bring VBOOT+measured boot to platforms missing it on coreboot mainline (xx30 and xx20). 

Doing so, heads and coreboot are using different PCRs.

Two options here, we have coreboot patched so that measuring scheme of heads don't change.

Or we change heads measuring scheme to match coreboot's.

We have to take a decision.

@MrChromebox @PatrickRudolph

**Comment by tlaurion** [comment]
@MrChromebox @PatrickRudolph we need to take a decision for things to move on and development to go ahead.

To minimize heads change, it seems that coreboot should be patched. 

To facilitate maintainership, it seems that Heads should be modified. 

Coreboot 4.12 includes measured boot without vboot.

What do we do?

**Comment by MrChromebox** [comment]
@tlaurion to clarify, coreboot 4.12 provides the **option** to use measured boot with or without vboot. so we can support both versions if desired and space available.

Question is, is the PCR measurement performed by coreboot 4.12 less secure/optimal than that done by Heads currently? Or just different?

**Comment by tlaurion** [comment]
@MrChromebox this is answered [there](https://github.com/osresearch/heads/pull/709#issuecomment-646995150). Short answer is: different.

**Comment by tlaurion** [comment]
@PatrickRudolph @MrChromebox  : @osresearch [says](https://github.com/osresearch/heads/pull/721#issuecomment-657229884) that we should change Heads to match coreboot measuring scheme:

> Adapting the official vboot/coreboot PCR usage makes some sense to me, since maintaining coreboot patches is quite a bit of work and adding the TPM drivers to the various stages is a somewhat invasive change.
> 
> Using one PCR for all of the stages also seems fine, especially if there is an event log that validates what went into the measurements. Having separate ones in the Heads design was mostly out of laziness on my part for ease of precomputation.
> 

@PatrickRudolph @pietrushnic this one is for yous:
> If Bootguard is enabled (in modes 2, 3, or 5), my understanding that PCR0 will be extended with the CRTM (the ACM and the IBB). Does this conflict with vboot's use of PCR0?

**Comment by miczyg1** [comment]
@tlaurion 
Measured Boot is now separately available under Security -> Trusted Platform Module. Enable Measured Boot option will appear when one of TPM families is enabled

For Boot Guard, besides the IBB, the PCR0 is extended with Boot Guard configuration, ACM SVN and signature, manifests signatures. And yes, that is a conflict with vboot's PCR0. AFAIK boot extends boot mode in PCR0 only.

**Comment by tlaurion** [comment]
@MrChromebox so how do we deal with PCR0 and adapting heads to coreboot measuring scheme following precedent comment?

**Comment by tlaurion** [comment]
@MrChromebox @PatrickRudolph disussion on implementation continues here https://github.com/osresearch/heads/pull/721#issuecomment-663992910

Should we close this PR?

**Comment by MrChromebox** [comment]
I feel like this PR can be rebased on top of #721, which would reduce it to simply board/config additions/changes

**Comment by PatrickRudolph** [comment]
I'd like to merge this feature once #721 is merged. As it's not required for measured boot it would be optional for now.

**Comment by tlaurion** [comment]
https://github.com/osresearch/heads/commit/28d3b7c89c114fccdf937f55ccce4397fa9338d1 being merged #721 #709 are next.
@MrChromebox @PatrickRudolph

**Comment by MrChromebox** [comment]
@tlaurion #721 is ready to go, but #709 definitely isn't. Either needs to be rebased on 4.12, or rebased to add support for coreboot 4.11 rather than replacing. I'd strongly advocate for the former, since I'm not sure there's any value to adding support for 4.11 at this time (we may want to for other boards than can't be updated to 4.12, eg KGPE-D16)

**Comment by tlaurion** [comment]
@PatrickRudolph this can be  resumed since #721 was merged.

**Comment by tlaurion** [comment]
@PatrickRudolph Any news?

**Comment by PatrickRudolph** [comment]
Any comments on the new commits?

**Comment by tlaurion** [comment]
@PatrickRudolph Will look into it tomorrow. Thanks! (Didn't see since not tagged, sorry for the delay)

**Comment by tlaurion** [comment]
@PatrickRudolph build successfull (x230-vboot and t430-vboot): https://app.circleci.com/pipelines/github/tlaurion/heads/393/workflows/1c587111-101b-418b-9918-413c5addc255/jobs/422

Requires the following change (would be nice that it is merged into this PR so its self-contained): 
- https://github.com/tlaurion/heads/commit/7b9b974c939d1f657b73e368238e84703a9c3ba5
- https://github.com/tlaurion/heads/commit/debdc19ecb64b8c3df18f41a428a905a621792fb

Artifacts: 
- [x230-vboot](https://422-103208611-gh.circle-artifacts.com/0/build/x230-vboot/coreboot.rom)
- [t430-vboot](https://422-103208611-gh.circle-artifacts.com/0/build/t430-vboot/coreboot.rom)

I will test x230-vboot in a bit, cannot test any other platforms.

**Comment by tlaurion** [comment]
@PatrickRudolph 

flashed x230-vboot.rom over #703 with `flashrom --force --noverify-all -p internal --ifd --image bios -w x230-boot.rom` resulting into a brick. Would have thought that would work, since IFD is maximized for BIOS while ME is minimized there, but I guess VBOOT should be flashed some other way. IS something special expected from x230-flash.rom, or should x230-flash-vboot exists? Is IFD supposed to be modified in some way?

**Comment by Tonux599** [comment]
@tlaurion 
> flashed [x230-vboot.rom](https://422-103208611-gh.circle-artifacts.com/0/build/x230-vboot/coreboot.rom) over #703 externally flashed x230 with `flashrom --force --noverify-all -p internal --ifd --image bios -w x230-boot.rom` resulting into a brick.

That brick may be related to this response [here](https://mail.coreboot.org/hyperkitty/list/coreboot@coreboot.org/message/DGG2CEJKVMWJJCADQPXYFSWPSCTKB4JI/) in which vboot is not functional when using a read-only flashmap. I have replied to the [thread](https://mail.coreboot.org/hyperkitty/list/coreboot@coreboot.org/thread/PITLZAHCODCQH4EIO76UZXXCJJ36ENGH/?sort=date) to see if the behaviour that is described by Julius applies to coreboot 4.12 as well as 4.11 and will update here when I know.

**Comment by tlaurion** [comment]
@PatrickRudolph so this is not functional as of now.

**Comment by Tonux599** [comment]
@tlaurion worth noting that that error is the same as the one we were getting when trying to make KGPE-D16 + coreboot 4.11 + vboot.

**Comment by tlaurion** [comment]
@Tonux599 : that was fixed in https://circleci.com/api/v1.1/project/github/tlaurion/heads/620/output/139/0?file=true&allocation-id=5f9c17bd45255007fb8bb449-0-build%2F2737844C

with https://github.com/tlaurion/heads/commit/7afdc235953f438b110f55bbe1a6805d9e745439

Unfortunately, it comes with another error, saying that musl-cross-make is not providing` /root/project/crossgcc/bin/i386-linux-musl-gnatbind`

**Comment by alexmaloteaux** [comment]
> Unfortunately, it comes with another error, saying that musl-cross-make is not providing` /root/project/crossgcc/bin/i386-linux-musl-gnatbind`

Here is how i compiled heads with coreboot 4.12 for t430.

- changed board config to use 4.12 and then got musl-gnatbind not found issue
- compiled muslc latest (actual one in heads will fail on ada compiler) on ubuntu 20.04(18.04 wont work due to old gnat version) with those commands
 
```
make TARGET=x86_64-linux-musl GCC_CONFIG="--enable-languages=ada,c,c++" FULL_GCC_CONFIG="--enable-languages=ada,c,c++"  -j $(($(nproc --all) + 1))  install
make TARGET=i386-linux-musl GCC_CONFIG="--enable-languages=ada,c,c++" FULL_GCC_CONFIG="--enable-languages=ada,c,c++"  -j $(($(nproc --all) + 1))  install
```

- Create inside heads this folder crossgcc/x86_64-linux-musl and copy the file from output in musl-cross-make there. 

- launch heads compilation with 
`make TOOLCHAIN=$(pwd) BOARD=t420 V=s`

- Coreboot compilation failed , and i had to add this line to build/coreboot-4.12/Makefile.inc
`CFLAGS_common += Wno-address-of-packed-member`

-relaunched compilation and it failed again with relocation type 10 on ramstage.debug, for this we need to disable RELOCATABLE_RAMSTAGE, alternatively i removed the  step in src/arch/x86/Makefile.inc

from there at least it compiled , but i faced permament black screen while the board stays powered on as opposed to #897

**Comment by tlaurion** [comment]
@zaolin @PatrickRudolph that was supposed to be paid when functional and mergeable.

**Comment by tlaurion** [comment]
Won't be used, vboot too big to be usable and measured boot chosen instead. Could be revisited per opening an issue. Tagging as not planned and won't fix.

**Pull request closed without merging**
