### PR TITLE
Most boards: linux kernel version bump to 6.1.8 (to match librems)

### LINKED ISSUE #1796: Kernel too old for mounting /boot produced by Qubes 4.3 / Fedora 41
### A. Provide Hardware Details

1. What board are you using? (Choose from the list of boards [here](https://github.com/eganonoa/heads/tree/master/boards))

2. Does your computer have a dGPU or is it iGPU-only?
    - [ ] dGPU (Distinct GPU other then internal GPU)
    - [ ] iGPU-only (Internal GPU, normally Intel GPU)

3. Who installed Heads on this computer?
    - [ ] Insurgo (Issues to be reported at https://github.com/linuxboot/heads/issues)
    - [ ] Nitrokey (Issues to be reported at https://github.com/Nitrokey/heads/issues)
    - [ ] Purism (Issues to be reported at https://source.puri.sm/firmware/pureboot/-/issues)
    - [ ] Novacustom (Issues to be reported at https://github.com/Dasharo/dasharo-issues)
    - [ ] HardnenedVault (Issues to be reported at https://github.com/hardenedvault/vaultboot/issues)
    - [ ] Other provider
    - [x] Self-installed

4. What PGP key is being used?
    - [ ] Librem Key (Nitrokey Pro 2 rebranded)
    - [ ] Nitrokey Pro
    - [x] Nitrokey Pro 2
    - [ ] Nitrokey 3 NFC
    - [ ] Nitrokey 3 NFC Mini
    - [ ] Nitrokey Storage
    - [ ] Nitrokey Storage 2
    - [ ] Yubikey
    - [ ] Other

5. Are you using the PGP key to provide HOTP verification?
    - [x] Yes
    - [ ] No
    - [ ] I don't know

### B. Identify how the board was flashed

1. Is this problem related to updating heads or flashing it for the first time?
    - [ ] First-time flash
    - [x] Updating heads 

2. If the problem is related to an update, how did you attempt to apply the update?
    - [x] Using the Heads menus
    - [ ] Flashrom via the Recovery Shell
    - [ ] External flashing

3. How was Heads initially flashed?
    - [x] External flashing
    - [ ] Internal-only / 1vyprep+1vyrain / skulls
    - [ ] Don't know

4. Was the board flashed with a maximized or non-maximized/legacy rom?
    - [x] Maximized
    - [ ] Non-maximized / legacy
    - [ ] I don't know

5. If Heads was externally flashed, was IFD unlocked?
    - [ ] Yes
    - [ ] No
    - [ ] Don't know

### C. Identify the rom related to this bug report

1. Did you download or build the rom at issue in this bug report?
    - [ ] I downloaded it
    - [x] I built it

2. If you downloaded your rom, where did you get it from?
    - [ ] Heads CircleCi
    - [ ] Purism
    - [ ] Nitrokey
    - [ ] Dasharo DTS (Novacustom)
    - [ ] Somewhere else (please identify)

    *Please provide the release number or otherwise identify the rom downloaded*

3. If you built your rom, which repository:branch did you use?
    - [x] Heads:Master (3fef9e06c1bb9de81a170e747282ab5cea879360)
    - [ ] Other (please identify)

4. What version of coreboot did you use in building?
{ You can find this information from github commit ID or once flashed, by giving the complete version from Sytem Information under Options --> menu}

5. In building the rom, where did you get the blobs?
    - [ ] No blobs required
    - [ ] Provided by the company that installed Heads on the device
    - [ ] Extracted from a backup rom taken from this device
    - [ ] Extracted from another backup rom taken from another device (please identify the board model)
    - [ ] Extracted from the online bios using the automated tools provided in Heads
    - [ ] I don't know

## Please describe the problem

**Describe the bug**

Mounting /boot read-write fails with `couldn't mount RDWR because of unsupported optiional features (10000)`

**To Reproduce**
1. Install Qubes 4.3 (for example https://qubes.notset.fr/iso-testing/Qubes-4.3.202409102200-x86_64.iso, or one of openQA iso)
2. Try to reset TPM
3. Observe it failing

**Expected behavior**

Should mount /boot normally

**Screenshots**

heads-fs

**Additional context**

Looks like 5.10 kernel is still too old for this.

### PR DESCRIPTION
**Pull request by tlaurion**
Kernel version bump to kernel 5.15+ needed to fix #1796 (all boards but Talos II which is separate effort under #1802)

So we reuse linux kernel 6.1.8 + librem common 6.1.8 as a base, picked by Purism for their boards and uniformize once more.

-- 

This PR: 
- Deprecates legacy boards (kernel too big, would need another pass of #590 which is definitely out of scope unless funding).
  - Adds global Makefile helper to move board to unmaintainde_boards, ci config still needs manual cleaning 
  - linux configs touched tough, through git diff > patch and seds
- Unification librems<->other boards based on 6.1.8 (x230<->qemu<->librems_common-6.1.8) 

Specifically:
- Streamline modules/linux Makefile helpers so that one asks on console for new Kconfig options to be y/n, another one to do olddefconfig (accept new defaults)
  - Exercice proves again that oldconfig exposes new things added into kernel by default as opposed to defconfig format.
- Add TCP Syn cookies to librems common (all boards add CDC tethering AFAIK. Add this protection by default)
- Remove unneeded network card drivers from librems common and unify
- Remove unneeded microsoft surface drivers from librems common and unify
- Remove WMI embedded Binary MOF driver CONFIG_WMI_BMOF
- Unify removed Kconfig options from x230 ported to 6.1.8 to librems common
- Verify qemu (AMD) changes working (note, there is clock source watchdog that would need to be investigated seperately for QEMU TCG mode, that is, not KVM)
- Review crypto backend requirements/unify once more
- Removed bunch of unused stuff under QEMU Q35 (AMD)

----

Q/A:
- CONFIG_RANDSTRUCT_NONE vs CONFIG_RANDSTRUCT_FULL? CONFIG_RANDSTRUCT_NONE now, perf impact otherwise: don't have time to test this.
- CONFIG_LDISC_AUTOLOAD=y?
- CONFIG_PTP_1588_CLOCK_OPTIONAL=y?
- CONFIG_X86_THERMAL_VECTOR=y?
- ACPI-WMI (Windows Management Instrumentation) mapper device (PNP0C14) enabled by ACPI_VIDEO and depended by DRM drivers.
  - ACPI_VIDEO seems needed.
- CONFIG_INPUT_VIVALDIFMAP=y anabled by CONFIG_KEYBOARD_ATKBD (AT/PS2 Keyboard)

----

Notable differences between librems common-6.1.8 vs other linux configs in tree:
- mei (kernel module to interact with ME/CSME) : deactivated on librems
- retpoline deactivated on librems
- mouse input enabled on sandy/ivy/haswell+ because refurbished devices/second hand and knowing mousepad/trackpad fails is needed for OEM/refurbishers to test this prior of shipping (oem-system-info-xx30 script)
- USB OHCI and dependencies build as kernel modules on sandy/ivy/haswell etc (USB1.1 controllers support)
- MMC (multi memory card reader) support in sandy/ivy/haswell +

**config/linux-librem_common.conf: applied seds and patches but unverified. This is used by librem_l1um, left for @JonathonHall-Purism to validate changes he wants there comparing with other 6.1.8 based boards linux configs which need kernel version bump otherwise #1796.**

---

Changes applied to librems:
- TCP SYN cookies activated (CDC tethering offered, should be enabled by best practices)
- deactivated compiled in network drivers that have no known reasons to be there (should be compiled as modules in all cases anyway)

### CODE REVIEW

**Comment by tlaurion** [comment]
Needs review (eyes)

**Review by JonathonHall-Purism — APPROVED** [review]
Tested Librem 14, L1UM v1, and L1UM v2.  Looks good to me :+1:

**Comment by tlaurion** [comment]
Review OptiPlex

**Comment by tlaurion** [comment]
Merge #1541 first

**Comment by tlaurion** [comment]
Hmmm. Commits logs (kernel version bump is happening, yes, but not from same origin version), while rebasing cannot be performed. 

Did a merge commit of master into this PR under [6385a95](https://github.com/linuxboot/heads/pull/1803/commits/6385a95368695f96c9f41a82b395d44cb284d020), clean enough or have to redo this whole PR @JonathonHall-Purism ? (There were conflicts since we kernel version bumped for cryptsetup with #1541)

**Comment by JonathonHall-Purism** [comment]
@tlaurion I'm fine merging as-is with the merge commit in this branch.  Thanks for pointing it out, sorry for the delay in my reviews recently that caused these conflicts.  :bow:

**Pull request merged**
