### PR TITLE
V560tu/v540tu/nv4x_adl/ns50 needed staging fixups

### PR DESCRIPTION
**Pull request by tlaurion**
input for #1846, taking missing commits + adaptations from #1871 so we have builds from CI to test and report on @mkopec

### CODE REVIEW

**Comment by tlaurion** [comment]
Not important, but CircleCI's v540tu/v650tu should depend on x230-hotp-maximized not n4x_adl. Gain in time is minimal reusing nv4x_adl build cache; important here is to reuse crosggc buildstack cached from x230-hotp-maximized, outside of that gains in compilation time is minimal at the cost of passing another unneeded layer of workspace cache.

**Comment by tlaurion** [comment]
@mkopec bootloop still with https://output.circle-artifacts.com/output/job/74d3cd5e-9da5-460d-9a29-ea34d475a781/artifacts/0/build/x86/novacustom-v560tu/hashes.txt

repro:
- flashed from stock rom, which I produced screenshot before, with  `--ifd -i bios -i me -i fd`
- Let it do its thing. 2 reboots without backlit whitish screen (Guess is memory training)
- 3rd reboot: whitish backlit. Each reboot is happening after 90s after power led lights up to reboot. Watchguard of some sort??

Nothing I can report more here unfortunately. Can you replicate that this firmware works the same way on your side?
Haven't upgrade EC or anything else here. Whatever you have done to this test laptop that I haven't outside of flashing firmware with built rom would be appreciated to be communicated to me here. OR a test rom built with logs stored into CBFS to be backup and shared off channel to you or anything you see fit to unblock this. Let me know.

**Comment by tlaurion** [comment]
@mkopec 

```
python: can't open file '/home/user/heads/build/x86/coreboot-dasharo/3rdparty/fsp/Tools/SplitFspBin.py': [Errno 2] No such file or directory
make[1]: *** [src/drivers/intel/fsp2_0/Makefile.mk:112: novacustom-v560tu/Fsp_M.fd] Error 2
```

**Comment by mkopec** [comment]
Managed to reproduce the freeze, it's freezing while attempting to disable ME: 

```
[DEBUG]  me_state = 2
[DEBUG]  CMOS: me_state = 4294967295
[DEBUG]  ME needs to be disabled.
[ERROR]  HECI: not ready
```

> python: can't open file '/home/user/heads/build/x86/coreboot-dasharo/3rdparty/fsp/Tools/SplitFspBin.py': [Errno 2] No such file or directory
> make[1]: *** [src/drivers/intel/fsp2_0/Makefile.mk:112: novacustom-v560tu/Fsp_M.fd] Error 2

Need to run `git submodule update` in side the coreboot dir

**Comment by tlaurion** [comment]
Closing this. Still having this python error, but this is not what this PR was about. Closing

**Pull request closed without merging**
