### PR TITLE
add nvme support kgpe-d16

### PR DESCRIPTION
**Pull request by arhabd**
add nvme support works as boot device hopefully

### CODE REVIEW

**Comment by tlaurion** [comment]
@arhabd thanks for your contribution

1- Is this tested working?
2- Please sign commits as explained under DCO error of this PR under https://github.com/linuxboot/heads/runs/27754458416

**Comment by arhabd** [comment]
> @arhabd thanks for your contribution
> 
> 1- Is this tested working? 2- Please sign commits as explained under DCO error of this PR under https://github.com/linuxboot/heads/runs/27754458416

my git diff displays like this but i only added the nvme related diffs
https://pb.envs.net/?8e3f8bf2efa48b6e#DqKt9A5vifrV4vgkhxDcVhMh2KLq839TS7KNZYjHoNLx

i can boot my m.2 nvme drive connected to a pcie adapter using this i did the commit through the gui i dont have github account setup on my local git is it required? can i sign it though the github website?

**Comment by tlaurion** [comment]
> Will test [#1719 (comment)](https://github.com/linuxboot/heads/pull/1719#issuecomment-2250411862) against his PR which needs to be rebased on master

@SergiiDmytruk there must be something I miss, since I cannot apply your suggestion above
```
git push arhabd patch-1 -f
error: src refspec patch-1 does not match any
error: failed to push some refs to 'https://github.com/arhabd/heads'
```


Superseeded by #1738

**Comment by tlaurion** [comment]
I do not see any reason to not apply the patch to other linux configs used by kgpe-d16 variants.

**Comment by SergiiDmytruk** [comment]
@tlaurion

> `error: src refspec patch-1 does not match any`

Sounds like you don't have a local branch with that name, something like `HEAD:patch-1` should fix this if you want to push the current branch.

**Pull request closed without merging**
