### PR TITLE
config/linux-librem_common-6.1.8: Rebuild starting with 5.10 config

### PR DESCRIPTION
**Pull request by JonathonHall-Purism**
Rebuild the kernel 6.1.8 config for Librem devices starting from the current 5.10 config as a base.  The current 5.10 config had cleaned up some unneeded options, but that hadn't been carried over to the 6.1.8 config.

Graphics init still uses EFIFB in the 6.1.8 kernel.  5.10 keeps DRM+ast to support librem_l1um (the only board still using it).

### CODE REVIEW

**Comment by JonathonHall-Purism** [comment]
Smoke tested librem_14, librem_15v4 (4K framebuffer boot), librem_l1um_v2 (ast framebuffer boot).  Booted memtest86+ on all to verify framebuffer works, since it has been a pain point in the past.

**Comment by tlaurion** [comment]
@JonathonHall-Purism 

Quickly chekced and compared, where shared config for x230 is older and hard to directly compare.
Saved changes from librem shared ocnfig back to oldconfig and came out with

```
diff --git a/config/linux-librem_common-6.1.8.config b/config/linux-librem_common-6.1.8.config
index 9d83a8db209..88b6a845105 100644
--- a/config/linux-librem_common-6.1.8.config
+++ b/config/linux-librem_common-6.1.8.config
@@ -885,10 +885,10 @@ CONFIG_PCI=y
 CONFIG_PCI_DOMAINS=y
 # CONFIG_PCIEPORTBUS is not set
 CONFIG_PCIEASPM=y
-CONFIG_PCIEASPM_DEFAULT=y
+# CONFIG_PCIEASPM_DEFAULT is not set
 # CONFIG_PCIEASPM_POWERSAVE is not set
 # CONFIG_PCIEASPM_POWER_SUPERSAVE is not set
-# CONFIG_PCIEASPM_PERFORMANCE is not set
+CONFIG_PCIEASPM_PERFORMANCE=y
 # CONFIG_PCIE_PTM is not set
 CONFIG_PCI_MSI=y
 CONFIG_PCI_MSI_IRQ_DOMAIN=y
@@ -1106,9 +1106,9 @@ CONFIG_BLK_DEV_NVME=y
 #
 # Altera FPGA firmware download module (requires I2C)
 #
-# CONFIG_INTEL_MEI is not set
-# CONFIG_INTEL_MEI_ME is not set
-# CONFIG_INTEL_MEI_TXE is not set
+CONFIG_INTEL_MEI=m
+CONFIG_INTEL_MEI_ME=m
+CONFIG_INTEL_MEI_TXE=m
 # CONFIG_VMWARE_VMCI is not set
 # CONFIG_GENWQE is not set
 # CONFIG_ECHO is not set
@@ -2590,7 +2590,7 @@ CONFIG_CRYPTO_SIMD=y
 #
 # Block ciphers
 #
-# CONFIG_CRYPTO_AES is not set
+CONFIG_CRYPTO_AES=y
 # CONFIG_CRYPTO_AES_TI is not set
 # CONFIG_CRYPTO_ARIA is not set
 # CONFIG_CRYPTO_BLOWFISH is not set
```

Quickly, 
- CONFIG_CRYPTO_AES is required for cryptsetup cryptobackend at reencryption
- CONFIG_PCIEASPM_PERFORMANCE is suggested to gain fastest PCIE perf on newer hardware
- MEI not sure why removed?

Otherwise LGTM

**Review by tlaurion — APPROVED** [review]
@JonathonHall-Purism 

Quickly checked and compared, where shared config for x230 is older and hard to directly compare.
Saved changes from librem shared ocnfig back to oldconfig and came out with

```
diff --git a/config/linux-librem_common-6.1.8.config b/config/linux-librem_common-6.1.8.config
index 9d83a8db209..88b6a845105 100644
--- a/config/linux-librem_common-6.1.8.config
+++ b/config/linux-librem_common-6.1.8.config
@@ -885,10 +885,10 @@ CONFIG_PCI=y
 CONFIG_PCI_DOMAINS=y
 # CONFIG_PCIEPORTBUS is not set
 CONFIG_PCIEASPM=y
-CONFIG_PCIEASPM_DEFAULT=y
+# CONFIG_PCIEASPM_DEFAULT is not set
 # CONFIG_PCIEASPM_POWERSAVE is not set
 # CONFIG_PCIEASPM_POWER_SUPERSAVE is not set
-# CONFIG_PCIEASPM_PERFORMANCE is not set
+CONFIG_PCIEASPM_PERFORMANCE=y
 # CONFIG_PCIE_PTM is not set
 CONFIG_PCI_MSI=y
 CONFIG_PCI_MSI_IRQ_DOMAIN=y
@@ -1106,9 +1106,9 @@ CONFIG_BLK_DEV_NVME=y
 #
 # Altera FPGA firmware download module (requires I2C)
 #
-# CONFIG_INTEL_MEI is not set
-# CONFIG_INTEL_MEI_ME is not set
-# CONFIG_INTEL_MEI_TXE is not set
+CONFIG_INTEL_MEI=m
+CONFIG_INTEL_MEI_ME=m
+CONFIG_INTEL_MEI_TXE=m
 # CONFIG_VMWARE_VMCI is not set
 # CONFIG_GENWQE is not set
 # CONFIG_ECHO is not set
@@ -2590,7 +2590,7 @@ CONFIG_CRYPTO_SIMD=y
 #
 # Block ciphers
 #
-# CONFIG_CRYPTO_AES is not set
+CONFIG_CRYPTO_AES=y
 # CONFIG_CRYPTO_AES_TI is not set
 # CONFIG_CRYPTO_ARIA is not set
 # CONFIG_CRYPTO_BLOWFISH is not set
```

Quickly, 
- CONFIG_CRYPTO_AES is required for cryptsetup cryptobackend at reencryption
- CONFIG_PCIEASPM_PERFORMANCE is suggested to gain fastest PCIE perf on newer hardware
- MEI not sure why removed?

Otherwise LGTM!

**Comment by JonathonHall-Purism** [comment]
Thanks @tlaurion I will check CRYPTO_AES and PCIEASPM_PERFORMANCE again before merging, good notes.

MEI is removed because the HECI devices are disabled on all Librems (all either have HAP bit or neutralized ME).

AFAICT, there also are no boards actually setting CONFIG_LINUX_MEI in the board config (so mei.ko/mei-me.ko are never actually bundled), and I don't see any logic to insert those modules if they were bundled.  So I don't think =m makes sense for the other Linux configs either.

**Comment by tlaurion** [comment]
> MEI is removed because the HECI devices are disabled on all Librems (all either have HAP bit or neutralized ME).
> 
> AFAICT, there also are no boards actually setting CONFIG_LINUX_MEI in the board config (so mei.ko/mei-me.ko are never actually bundled), and I don't see any logic to insert those modules if they were bundled. So I don't think =m makes sense for the other Linux configs either.

Right checked linux configs, linux module and board statements.


Some boards's linux config compile as kernel modules:
```
CONFIG_INTEL_MEI=m
CONFIG_INTEL_MEI_ME=m
CONFIG_INTEL_MEI_TXE=m
```

Where modules/linux:
```
# ME drivers for talking the the management engine
linux_modules-$(CONFIG_LINUX_MEI)       += drivers/misc/mei/mei.ko
linux_modules-$(CONFIG_LINUX_MEI)       += drivers/misc/mei/mei-me.ko
```

But where no boards configs actually include `CONFIG_LINUX_MEI`. Basically an old artifact of older times where ME got investigated to be neutered/deactivated/removed. I think we should add verification of platform runtime somehow with at least cbmem to check runtime ME state in another issue? @JonathonHall-Purism ?

**Comment by JonathonHall-Purism** [comment]
@tlaurion I checked out CONFIG_CRYPTO_AES and CONFIG_PCIEASPM_PERFORMANCE.

CONFIG_CRYPTO_AES adds the "generic" implementation of AES.  We already get the AES-NI implementation from CONFIG_CRYPTO_AES_NI_INTEL, which is preferred over the generic implementation, and all of the boards using this kernel support AES-NI.  So I don't see any reason this would be needed (cryptsetup reencrypt works as-is).  We didn't get it before this PR either, it was set to 'm' and we weren't shipping the module.

CONFIG_PCIEASPM_PERFORMANCE increases idle power draw too much.  On Librem 11 (smallest battery, most sensitive to power consumption), the idle power draw increased from 7.5 W to 8.1 W.  I did not check for any change in reencrypt throughput but I don't want to enable it across the board due to the increased power.  Again, no change compared to the state prior to the MR here either.

So no changes are needed.  Unless you have something else to discuss, I'll assume the existing approval stands and merge :+1:

**Pull request merged**
